apiVersion: batch/v1
kind: Job
metadata:
  name: installplan-approver
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.4
          command:
            - /bin/bash
            - -c
            - |
              export HOME=/tmp/approver
              echo "Approving operator install.  Waiting a few seconds to make sure the InstallPlan gets created first."
              sleep $SLEEP
              installplan=$(oc get installplan -n openshift-operators | grep -i service-binding-operator.v0.8.0 | awk '{print $1}'); echo "installplan: $installplan"
              count=0

              if [[ "$installplan" != "" ]]; then
                echo "patching install plan: $installplan"
                $(oc patch installplan $installplan -n openshift-operators --type merge --patch '{"spec":{"approved":true}}')

                until [[ $(oc get installplan $installplan -o jsonpath="{.spec.approved}" -n openshift-operators) == "true" ]] || [[ $count -eq 6 ]]; do
                  count=$((count + 1))
                  sleep 60
                done

              fi

              if [[ $count -eq 6 ]]; then
                echo "Timed out waiting for SBO installplan to be approved"
                exit 1
              fi
          imagePullPolicy: Always
          name: installplan-approver
          env:
            - name: SLEEP
              value: "1m"
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: installplan-approver-job
      serviceAccountName: installplan-approver-job
      terminationGracePeriodSeconds: 30
